

POST localhost:8001/v1/item/add
Content-Type: application/json

{
  "id": "",
  "name": "",
  "description": "ddescription",
  "count" : 100
}

###
POST localhost:8001/v1/item/add/C
Content-Type: application/json

{
"id": "12223",
"name": "12223",
"description": "description",
"count" : 100
}


###
POST localhost:8070/v1/item/add/C
Content-Type: application/json

{
  "id": "12223",
  "name": "12223",
  "description": "description",
  "count" : 100
}






